[workspace]
members = ["minigu/binder", "minigu/catalog", "minigu/common"]
resolver = "3"

[workspace.package]
edition = "2024"

[workspace.lints.clippy]
correctness = "deny"
suspicious = "warn"
complexity = "warn"
perf = "warn"
style = "warn"

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
