[workspace]
members = [
  # System-level tests
  "minigu-test",

  # Internal
  "minigu/binder",
  "minigu/catalog",
  "minigu/common",
  "minigu/parser",
  "minigu/storage",
]
resolver = "3"

[workspace.package]
edition = "2024"

[workspace.lints.clippy]
correctness = "deny"
suspicious = "warn"
complexity = "warn"
perf = "warn"
style = "warn"

[workspace.dependencies]
insta = { version = "1.42.2", features = ["yaml"] }
divan = "0.1.17"
paste = "1.0.15"

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
