comment_width = 120
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
style_edition = "2024"
tab_spaces = 4
wrap_comments = true
