[package]
name = "wal"
version = "0.1.0"
edition.workspace = true

[dependencies]
prost = "0.13.5"
crc32fast = "1.4.2"
chrono = "0.4.40"
tokio = { version = "1.43.0", features = ["full"] }

[build-dependencies]
prost-build = "0.13.5"

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
