[package]
edition.workspace = true
name = "minigu"
version = "0.1.0"

[dependencies]
gql-parser = { workspace = true }
miette = { workspace = true }
thiserror = { workspace = true, features = ["std"] }

[lints]
workspace = true
