[package]
edition.workspace = true
name = "minigu-common"
version = "0.1.0"

[dependencies]
arrow = { workspace = true }
itertools = { workspace = true }
ordered-float = { version = "5.0.0", features = ["serde"] }
paste = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
