[package]
edition.workspace = true
name = "minigu-binder"
version = "0.1.0"

[dependencies]
gql-parser = { workspace = true }
serde = { workspace = true, features = ["std"] }
thiserror = { workspace = true, features = ["std"] }

[lints]
workspace = true
