[package]
edition.workspace = true
license.workspace = true
name = "minigu-python"
repository.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib"]
name = "minigu_python"

[dependencies]
pyo3 = { version = "0.24.1", features = ["extension-module"] }

[lints]
workspace = true
