[package]
edition.workspace = true
license.workspace = true
name = "minigu-python"
repository.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib"]
name = "minigu_python"

[dependencies]
arrow = { workspace = true }
minigu = { workspace = true }
minigu-catalog = { workspace = true }
minigu-common = { workspace = true }
minigu-context = { workspace = true }
minigu-storage = { workspace = true }
pyo3 = { version = "0.24.2", features = ["extension-module", "abi3-py37"] }
serde_json = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
pyo3 = { version = "0.24.2", features = ["auto-initialize", "extension-module", "abi3-py37"] }

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = [
    "minigu",
    "minigu-common",
    "minigu-context",
    "minigu-catalog",
    "minigu-storage",
    "serde_json",
]
