[package]
edition.workspace = true
license.workspace = true
name = "minigu-python"
repository.workspace = true
version.workspace = true

[lib]
name = "minigu_python"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { workspace = true, features = ["extension-module"] }
minigu = { workspace = true }
minigu-common = { workspace = true }
minigu-context = { workspace = true }
minigu-catalog = { workspace = true }
minigu-storage = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true