[package]
build = "build.rs"
edition.workspace = true
license.workspace = true
name = "minigu-python"
repository.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib"]
name = "minigu_python"

[dependencies]
minigu = { workspace = true }
minigu-catalog = { workspace = true }
minigu-common = { workspace = true }
minigu-context = { workspace = true }
minigu-storage = { workspace = true }
pyo3 = { workspace = true, features = ["extension-module", "abi3"] }
serde_json = { workspace = true }

[build-dependencies]
pyo3-build-config = { workspace = true }

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = [
    "minigu",
    "minigu-common",
    "minigu-context",
    "minigu-catalog",
    "minigu-storage",
    "serde_json",
]
