[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=40", "wheel", "setuptools-rust"]

[project]
authors = [{ name = "miniGU Team" }]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Rust",
]
description = "A graph database for learning purposes"
name = "minigu"
readme = "README.md"
requires-python = ">=3.6"
version = "0.1.0"

[project.urls]
Homepage = "https://github.com/TuGraph-family/miniGU"
Repository = "https://github.com/TuGraph-family/miniGU"

[tool.setuptools.packages.find]
include = ["minigu*"]
where = ["."]

[tool.setuptools.package-data]
minigu = ["*.pyd", "*.so", "*.dll"]
