[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.aarch64-pc-windows-msvc]
linker = "link.exe"

[target.aarch64-apple-darwin]
# For macOS ARM64, specify the linker explicitly
linker = "cc"