[package]
edition.workspace = true
name = "storage"
version = "0.1.0"

[dev-dependencies]
rand = "0.9.1"
serial_test = "3.2.0"

[dependencies]
bytes = "1.10.0"
chrono = "0.4.40"
crc32fast = "1.4.2"
crossbeam-epoch = "0.9"
crossbeam-skiplist = "0.1"
dashmap = "6.1"
minigu-common = { workspace = true }
postcard = { version = "1.1.1", features = ["alloc"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0.0"
uuid = { version = "1.7.0", features = ["v4", "serde"] }

[lints]
workspace = true
