name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1
  CI: true
  DEFAULT_FEATURES: "std,serde,miette"

defaults:
  run:
    shell: bash

jobs:
  typos:
    name: Spell Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: crate-ci/typos@v1.29.4

  toml:
    name: TOML Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: taiki-e/install-action@v2
      with:
        tool: taplo-cli@0.9.3
    - run: taplo fmt --check --diff

  fmt:
    name: Format Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - run: cargo fmt --check

  clippy:
    name: Clippy Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - run: cargo clippy --tests --features ${{ env.DEFAULT_FEATURES }} --no-deps

  build:
    needs: [ typos, toml, fmt, clippy ]
    # strategy:
    #   matrix:
    #     os: [ ubuntu-latest, macos-latest, windows-latest ]
    # name: Build on ${{ matrix.os }}
    # runs-on: ${{ matrix.os }}
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: Swatinem/rust-cache@v2
    - run: cargo build --features ${{ env.DEFAULT_FEATURES }}

  build_no_std:
    needs: [ typos, toml, fmt, clippy ]
    name: Build gql-parser in no_std mode
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - run: rustup target add aarch64-unknown-none
    - uses: Swatinem/rust-cache@v2
    - run: cargo build -p gql-parser --target aarch64-unknown-none --no-default-features

  test:
    needs: [ typos, toml, fmt, clippy ]
    # strategy:
    #   matrix:
    #     os: [ ubuntu-latest, macos-latest, windows-latest ]
    # name: Test on ${{ matrix.os }}
    # runs-on: ${{ matrix.os }}
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-nextest@0.9.88
    - uses: Swatinem/rust-cache@v2
    - run: cargo nextest run --features ${{ env.DEFAULT_FEATURES }} --exclude sqllogictest::run_sqllogictest
    - run: cargo test --features ${{ env.DEFAULT_FEATURES }} --doc

  sqllogictest:
    needs: [typos, toml, fmt, clippy]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: Swatinem/rust-cache@v2

      - name: Run SQL Logic Tests
        run: cargo test -p minigu-test --test sqllogictest -- run_sqllogictest

      - name: Re-run with --nocapture on failure
        if: failure()
        run: cargo test -p minigu-test --test sqllogictest -- --nocapture run_sqllogictest

  docs:
    name: Build Docs
    needs: [ typos, toml, fmt, clippy ]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - run: cargo doc --lib --no-deps --features ${{ env.DEFAULT_FEATURES }}
